language: scala
scala:
- 2.11.8
sudo: false
jdk:
- oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION server/test client/test
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
deploy:
  provider: heroku
  api_key:
    secure: Dh3C/ySx8wlXypxovdGhDAUyfEqUgYrM7EZd4u4wk4m9stxPtpRpEb/AUsx35M9GaYvhVA3SaK8vT3w21DgwTLfcb+k1GdVQ8fn7/FFVosYTnzOwUtczASZ4SuBOYcirUljAiJE2H6ngAPDZxErrLWRmAGWKetBZ2Ff76CEdl9oNKAdSEldBJ8G4eUTu/tDh/Qgta9RM6XJgMBzArWQi/qHj/ol56rEhobS2A0eVnapNViJYrQzgI7htawpsayOtosieOOr4R1KCJIYi1PLRSZV587kNLUaEljalfAJzxu2rXd1+neVnyHysScIP9aSUt+ZqS41T95d96VXWmyjX35b+upNz5JzqUdv6kQ2+pyBcVGVl0HNaM3Jr6omT1i+kHewqIKoaJ1JtyPFu6jYUnkY51s7rSSr1NSlyiztCR9qHilm1KsznBuvUh3kh/m5OiaJpQJgfAtEYOlK4S0cwcGIcrEm8xW9nKqNhadV9huOw/gu1gUK643A2ZWMX7xeTjAfuOlk+cwqcMYesB2Se9F557zvi3I3zIu/d/5FotlQRACQ43l58K4IMOXXnEkvy+FNXyOIyFTdTNJ2R7tKBc2NFFDchxgq9IMfpCHRb2zUNYfBeeslks8TGVVBc6xJq5g78r9LBdFzO3hjpGmSih8zwRnWtSCKLXs4wjTIyfq4=
  app: gigiyy-spa
  on:
    repo: gigiyy/scalajs-spa-tutorial
